/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_admin_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/generate-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Map */
        post: operations["generate_map_admin_generate_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/save-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Map */
        post: operations["save_map_admin_save_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/load-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Map */
        post: operations["load_map_admin_load_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/seed-scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Scenario */
        post: operations["seed_scenario_admin_seed_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/set-field": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Field */
        post: operations["set_field_admin_set_field_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/advance-turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Turn Endpoint */
        post: operations["advance_turn_endpoint_admin_advance_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_admin_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dev-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dev Log */
        get: operations["get_dev_log_admin_dev_log_get"];
        put?: never;
        post?: never;
        /** Clear Dev Log */
        delete: operations["clear_dev_log_admin_dev_log_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIDifficulty
         * @enum {string}
         */
        AIDifficulty: "easy" | "medium" | "hard";
        /** Agent */
        Agent: {
            /** Agent Id */
            agent_id: string;
            /** Name */
            name: string;
            domain: components["schemas"]["CouncilRole"];
            /** Specialisations */
            specialisations: string[];
            /**
             * Risk Profile
             * @default 0.5
             */
            risk_profile: number;
            /**
             * Track Record
             * @default 0
             */
            track_record: number;
            /** Hiring Cost */
            hiring_cost: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** CanalMania */
        CanalMania: {
            /**
             * Triggered
             * @default false
             */
            triggered: boolean;
            /**
             * Windfall Received
             * @default 0
             */
            windfall_received: number;
            /**
             * Bubble Risk
             * @default 0
             */
            bubble_risk: number;
            /**
             * Bubble Burst
             * @default false
             */
            bubble_burst: boolean;
        };
        /** CanalParty */
        CanalParty: {
            /**
             * Influence
             * @default 50
             */
            influence: number;
            /**
             * Milestones Achieved
             * @default []
             */
            milestones_achieved: string[];
        };
        /** CanalSegment */
        CanalSegment: {
            /** Segment Id */
            segment_id: string;
            /** From Node */
            from_node: string;
            /** To Node */
            to_node: string;
            /** Waypoints */
            waypoints: components["schemas"]["Waypoint"][];
            /**
             * Railway Claimed
             * @default false
             */
            railway_claimed: boolean;
            /**
             * Construction Cost
             * @default 0
             */
            construction_cost: number;
            readonly status: components["schemas"]["SegmentStatus"];
        };
        /**
         * CanalTier
         * @enum {string}
         */
        CanalTier: "none" | "bronze" | "silver" | "gold";
        /** CityMap */
        CityMap: {
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["MapNode"];
            };
            /** Canal Segments */
            canal_segments: {
                [key: string]: components["schemas"]["CanalSegment"];
            };
            /**
             * Railway Segments
             * @default []
             */
            railway_segments: components["schemas"]["RailwaySegment"][];
            /**
             * Councillors
             * @default []
             */
            councillors: components["schemas"]["Councillor"][];
            /**
             * Factions
             * @default []
             */
            factions: components["schemas"]["Faction"][];
        };
        /**
         * CouncilRole
         * @enum {string}
         */
        CouncilRole: "finance" | "infrastructure" | "transport";
        /** Councillor */
        Councillor: {
            /** Councillor Id */
            councillor_id: string;
            /** Name */
            name: string;
            role: components["schemas"]["CouncilRole"];
            /** Political Alignment */
            political_alignment: string;
            /** Core Values */
            core_values: string[];
            /** Professional Background */
            professional_background: string;
            /** Value Tension */
            value_tension: string;
            /** Skills */
            skills: components["schemas"]["CouncillorSkill"][];
            /**
             * Decisions Made
             * @default 0
             */
            decisions_made: number;
            /**
             * Value Aligned Decisions
             * @default 0
             */
            value_aligned_decisions: number;
            /**
             * Milestones Achieved
             * @default []
             */
            milestones_achieved: string[];
            /** Profile */
            profile: string;
        };
        /** CouncillorSkill */
        CouncillorSkill: {
            /** Skill Name */
            skill_name: string;
            /** Description */
            description: string;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Experience Points
             * @default 0
             */
            experience_points: number;
        };
        /** DepartmentBudget */
        DepartmentBudget: {
            /**
             * Finance
             * @default 10000
             */
            finance: number;
            /**
             * Infrastructure
             * @default 5000
             */
            infrastructure: number;
            /**
             * Transport
             * @default 5000
             */
            transport: number;
        };
        /** Effect */
        Effect: {
            effect_type: components["schemas"]["EffectType"];
            target_type: components["schemas"]["TargetType"];
            /** Target Id */
            target_id: string;
            /** Value */
            value: number | string;
            /**
             * Delay Turns
             * @default 0
             */
            delay_turns: number;
            /** Description */
            description: string;
        };
        /**
         * EffectType
         * @enum {string}
         */
        EffectType: "metric_delta" | "budget_delta" | "construction_start" | "construction_advance" | "faction_mood" | "report_generate" | "railway_influence" | "canalparty_influence" | "aesthetic_delta" | "economy_delta" | "income_delta" | "council_extension";
        /** Faction */
        Faction: {
            /** Faction Id */
            faction_id: string;
            /** Name */
            name: string;
            /** Profile */
            profile: string;
            /**
             * Happiness
             * @default 60
             */
            happiness: number;
            /**
             * Population Weight
             * @default 1
             */
            population_weight: number;
            /** Transport Priorities */
            transport_priorities: string[];
            /** Political Sensitivities */
            political_sensitivities: string[];
            /**
             * Reaction Threshold
             * @default 10
             */
            reaction_threshold: number;
            /**
             * Canal Alignment
             * @default 0
             */
            canal_alignment: number;
            /**
             * Railway Alignment
             * @default 0
             */
            railway_alignment: number;
        };
        /** GameEvent */
        GameEvent: {
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["GameEventType"];
            /** Turn */
            turn: number;
            /** Cycle */
            cycle: number;
            /** Description */
            description: string;
            /** Player Id */
            player_id?: string | null;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * GameEventType
         * @enum {string}
         */
        GameEventType: "waypoint_complete" | "waypoint_blocked" | "segment_complete" | "network_effect" | "milestone_bronze" | "milestone_silver" | "milestone_gold" | "engineering_feat" | "canal_mania" | "canal_mania_burst" | "railway_activated" | "railway_crisis" | "election_survived" | "game_over" | "major_decision" | "agent_success" | "agent_failure" | "faction_swing" | "council_extension" | "connection_lost" | "claude_timeout" | "voice_fallback" | "auto_resolved";
        /** GameState */
        GameState: {
            /** Session Id */
            session_id: string;
            status: components["schemas"]["GameStatus"];
            /**
             * Cycle
             * @default 1
             */
            cycle: number;
            /**
             * Turn
             * @default 1
             */
            turn: number;
            /**
             * Game Length
             * @default 5
             */
            game_length: number;
            city_map: components["schemas"]["CityMap"];
            /** Players */
            players: {
                [key: string]: components["schemas"]["Player"];
            };
            metrics: components["schemas"]["Metrics"];
            /** Factions */
            factions: components["schemas"]["Faction"][];
            railway_party: components["schemas"]["RailwayParty"];
            canal_party: components["schemas"]["CanalParty"];
            canal_mania?: components["schemas"]["CanalMania"];
            /** Pending Reports */
            pending_reports?: {
                [key: string]: components["schemas"]["Report"][];
            };
            pending_vote?: components["schemas"]["Vote"] | null;
            /**
             * Pending Effects
             * @default []
             */
            pending_effects: [
                number,
                components["schemas"]["Effect"]
            ][];
            /**
             * Event Log
             * @default []
             */
            event_log: components["schemas"]["GameEvent"][];
            /**
             * Council Extensions Remaining
             * @default 3
             */
            council_extensions_remaining: number;
            /**
             * Turn Time Limit
             * @default 40
             */
            turn_time_limit: number;
            /**
             * Current Turn Extended
             * @default false
             */
            current_turn_extended: boolean;
            win_state?: components["schemas"]["WinState"] | null;
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "lobby" | "setup" | "in_game" | "game_over";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MapNode */
        MapNode: {
            /** Node Id */
            node_id: string;
            /** Name */
            name: string;
            node_type: components["schemas"]["NodeType"];
            /** Position */
            position: [
                number,
                number
            ];
            /**
             * Has Railway Station
             * @default false
             */
            has_railway_station: boolean;
            /**
             * Has Canal Wharf
             * @default false
             */
            has_canal_wharf: boolean;
        };
        /** Metrics */
        Metrics: {
            /**
             * Road Rage Index
             * @default 50
             */
            road_rage_index: number;
            /**
             * Canal Efficiency Index
             * @default 10
             */
            canal_efficiency_index: number;
            /**
             * Aesthetic Index
             * @default 40
             */
            aesthetic_index: number;
            /**
             * Citizen Happiness
             * @default 65
             */
            citizen_happiness: number;
            /**
             * Horse Pollution
             * @default 30
             */
            horse_pollution: number;
            /**
             * Accidents This Cycle
             * @default 0
             */
            accidents_this_cycle: number;
            /**
             * Projects Delayed
             * @default 0
             */
            projects_delayed: number;
            /**
             * Tradies Nonbilling
             * @default 0
             */
            tradies_nonbilling: number;
            /**
             * Road Freight Pct
             * @default 100
             */
            road_freight_pct: number;
            /**
             * Canal Freight Pct
             * @default 0
             */
            canal_freight_pct: number;
            /**
             * Rail Freight Pct
             * @default 0
             */
            rail_freight_pct: number;
            /**
             * Economy Index
             * @default 50
             */
            economy_index: number;
            /**
             * Cycle Income
             * @default 0
             */
            cycle_income: number;
            budget?: components["schemas"]["DepartmentBudget"];
            /**
             * Election Polling
             * @default 65
             */
            election_polling: number;
            /**
             * Cycles Survived
             * @default 0
             */
            cycles_survived: number;
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "port" | "industrial" | "residential" | "commercial" | "market";
        /** Player */
        Player: {
            /** Player Id */
            player_id: string;
            /** Name */
            name: string;
            role: components["schemas"]["CouncilRole"];
            /** @default human */
            player_type: components["schemas"]["PlayerType"];
            councillor: components["schemas"]["Councillor"];
            /**
             * Agents
             * @default []
             */
            agents: components["schemas"]["Agent"][];
            ai_difficulty?: components["schemas"]["AIDifficulty"] | null;
        };
        /**
         * PlayerType
         * @enum {string}
         */
        PlayerType: "human" | "ai";
        /** RailwayParty */
        RailwayParty: {
            /**
             * Influence
             * @default 20
             */
            influence: number;
            /** @default lobby */
            phase: components["schemas"]["RailwayPhase"];
            /**
             * Activation Threshold
             * @default 40
             */
            activation_threshold: number;
            /**
             * Lobbying Events
             * @default []
             */
            lobbying_events: string[];
            /**
             * Councillors
             * @default []
             */
            councillors: components["schemas"]["Councillor"][];
            /**
             * Railway Segments
             * @default []
             */
            railway_segments: components["schemas"]["RailwaySegment"][];
            /**
             * Budget
             * @default 0
             */
            budget: number;
        };
        /**
         * RailwayPhase
         * @enum {string}
         */
        RailwayPhase: "lobby" | "active";
        /** RailwaySegment */
        RailwaySegment: {
            /** Segment Id */
            segment_id: string;
            /** From Node */
            from_node: string;
            /** To Node */
            to_node: string;
            /** Waypoints */
            waypoints: components["schemas"]["Waypoint"][];
            status: components["schemas"]["SegmentStatus"];
        };
        /** Report */
        Report: {
            /** Report Id */
            report_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            report_type: components["schemas"]["ReportType"];
            /** Addressed To */
            addressed_to: string;
            domain: components["schemas"]["CouncilRole"];
            /** Options */
            options: components["schemas"]["ReportOption"][];
            /** @default pending */
            status: components["schemas"]["ReportStatus"];
            /**
             * Is Private
             * @default true
             */
            is_private: boolean;
            /**
             * Delegation Candidates
             * @default []
             */
            delegation_candidates: string[];
            /** Delegated To */
            delegated_to?: string | null;
            /** Decision */
            decision?: string | null;
            /** Conflict With */
            conflict_with?: string | null;
            /**
             * Defer Count
             * @default 0
             */
            defer_count: number;
            /** Deferred Until Turn */
            deferred_until_turn?: number | null;
            /**
             * Deferral Consequences
             * @default []
             */
            deferral_consequences: string[];
            /**
             * Escalated To Council
             * @default false
             */
            escalated_to_council: boolean;
            /**
             * Urgent
             * @default false
             */
            urgent: boolean;
            /** Turn Received */
            turn_received: number;
            /** Turn Deadline */
            turn_deadline: number;
        };
        /** ReportOption */
        ReportOption: {
            /** Option Id */
            option_id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Effects */
            effects: components["schemas"]["Effect"][];
            risk_level: components["schemas"]["RiskLevel"];
            /**
             * Agent Only
             * @default false
             */
            agent_only: boolean;
            /**
             * Is Forced
             * @default false
             */
            is_forced: boolean;
            /**
             * Value Signals
             * @default []
             */
            value_signals: string[];
            /**
             * Min Skill Level
             * @default 0
             */
            min_skill_level: number;
            /** Required Skill */
            required_skill?: string | null;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "pending" | "decided" | "delegated" | "deferred" | "escalated" | "auto_resolved";
        /**
         * ReportType
         * @enum {string}
         */
        ReportType: "scheduled" | "threshold" | "claude_event" | "agent_outcome";
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /**
         * SegmentStatus
         * @enum {string}
         */
        SegmentStatus: "proposed" | "approved" | "under_construction" | "complete";
        /**
         * TargetType
         * @enum {string}
         */
        TargetType: "metric" | "faction" | "segment" | "waypoint" | "railway_party" | "canal_party" | "player" | "agent" | "economy" | "freight_road" | "freight_canal" | "freight_rail" | "cycle_income";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vote */
        Vote: {
            /** Vote Id */
            vote_id: string;
            /** Report Ids */
            report_ids: string[];
            /** Initiated By */
            initiated_by: string;
            /** Options */
            options: components["schemas"]["ReportOption"][];
            /**
             * Votes
             * @default {}
             */
            votes: {
                [key: string]: string;
            };
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "resolved";
            /** Result */
            result?: string | null;
            /**
             * Mayor Tiebreaker
             * @default false
             */
            mayor_tiebreaker: boolean;
        };
        /** Waypoint */
        Waypoint: {
            /** Waypoint Id */
            waypoint_id: string;
            /** Name */
            name: string;
            waypoint_type: components["schemas"]["WaypointType"];
            /** Position */
            position: [
                number,
                number
            ];
            /** @default unstarted */
            status: components["schemas"]["WaypointStatus"];
            /** Blocked By */
            blocked_by?: string | null;
            /** Construction Turns Required */
            construction_turns_required: number;
            /**
             * Turns Spent
             * @default 0
             */
            turns_spent: number;
        };
        /**
         * WaypointStatus
         * @enum {string}
         */
        WaypointStatus: "unstarted" | "under_construction" | "complete" | "blocked" | "contested";
        /**
         * WaypointType
         * @enum {string}
         */
        WaypointType: "cutting" | "embankment" | "lock" | "aqueduct" | "tunnel" | "junction" | "amenity";
        /** WinState */
        WinState: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "game_over" | "survived" | "modest_win" | "strong_win" | "celebration" | "heritage_commendation";
            canal_tier: components["schemas"]["CanalTier"];
            /**
             * Heritage Commendation
             * @default false
             */
            heritage_commendation: boolean;
            /** Cycles Survived */
            cycles_survived: number;
            /** Epitaph */
            epitaph: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_state_admin_state_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_map_admin_generate_map_post: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_map_admin_save_map_post: {
        parameters: {
            query: {
                token: string;
                slot?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_map_admin_load_map_post: {
        parameters: {
            query: {
                token: string;
                slot?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_scenario_admin_seed_scenario_post: {
        parameters: {
            query: {
                token: string;
                scenario?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_field_admin_set_field_post: {
        parameters: {
            query: {
                token: string;
                field: string;
                value: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_turn_endpoint_admin_advance_turn_post: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_admin_usage_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dev_log_admin_dev_log_get: {
        parameters: {
            query: {
                token: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_dev_log_admin_dev_log_delete: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
